### ISSUE TITLE
select or create tags with TOM-SELECT.JS

### ISSUE THREAD

**Issue by yshmarov** [yshmarov/superails#20]
https://yarnpkg.com/package/tom-select
https://tom-select.js.org/
https://tom-select.js.org/
https://psmy.medium.com/rails-6-stimulus-and-select2-de4a4d2b59e4
https://slimselectjs.com/

**Comment by secretpray** [comment]
👌Good variant

**Comment by secretpray** [comment]
https://gist.github.com/secretpray/1a325b3d2616bcdde336bedda5f4bd16
